In [4]:
import numpy as np
import pickle
from sklearn.svm import SVC

In [5]:
X=np.zeros((31,7500))
for i in range(0,31):
    fp=open('data'+str(i)+'.pkl','rb')
    block=pickle.load(fp)
    fp.close
    #print(block[1:10])
    for j in range(0,7500):
        X[i,j]=int(block[j])
    print(X[i,1:10])

[72. 69. 68. 68. 69. 71. 73. 72. 71.]
[90. 90. 85. 81. 85. 87. 84. 80. 79.]
[63. 59. 62. 64. 66. 70. 71. 69. 65.]
[75. 74. 75. 75. 75. 75. 76. 78. 80.]
[33. 35. 36. 37. 38. 37. 34. 32. 32.]
[205. 207. 207. 208. 208. 208. 208. 208. 208.]
[154. 154. 154. 154. 155. 153. 152. 153. 157.]
[167. 169. 169. 170. 171. 172. 172. 171. 170.]
[82. 87. 85. 82. 80. 80. 81. 82. 83.]
[69. 71. 73. 74. 73. 72. 73. 72. 70.]
[4. 5. 4. 5. 5. 4. 6. 8. 8.]
[133. 132. 132. 133. 133. 133. 134. 135. 136.]
[41. 47. 51. 51. 51. 54. 58. 58. 55.]
[120. 122. 124. 124. 121. 121. 122. 124. 124.]
[86. 85. 86. 84. 82. 80. 80. 79. 77.]
[104. 102. 101. 105. 105.  96.  92.  94.  93.]
[ 98. 104. 103. 101. 100. 100. 101.  99.  97.]
[93. 91. 94. 96. 93. 91. 90. 88. 88.]
[48. 49. 45. 42. 45. 51. 50. 46. 48.]
[85. 88. 92. 94. 94. 94. 94. 94. 93.]
[55. 59. 62. 60. 56. 55. 53. 52. 54.]
[86. 84. 82. 78. 75. 75. 77. 80. 82.]
[74. 71. 70. 75. 78. 74. 77. 84. 84.]
[30. 39. 40. 39. 37. 35. 29. 24. 22.]
[42. 25. 24. 24. 26. 27. 26. 24. 2

In [6]:
Y=np.zeros((31))
Y[1]=1.0
Y[2]=1.0
Y[3]=1.0
Y[0]=1.0
Y[8]=1.0
Y[9]=1.0
Y[14]=1.0
Y[19]=1.0
Y[21]=1.0
Y[25]=1.0
Y[26]=1.0
Y[27]=1.0
#print(TrainingLabels[10])
#print(TrainingLabels)
#TrainingLabels=[1 1 1 1 1 1 1 1 1 1 
#                1 1 1 1 1 1 1 1 1 1 
#                1 1 1 1 1 1 1 1 1 1]

In [8]:
clf= SVC(C=200,kernel='rbf')
clf.fit(X,Y)
from sklearn.metrics import accuracy_score
prediction = clf.predict(X)
correct = accuracy_score(Y, prediction)
print(correct)

1.0


In [9]:
from sklearn.externals import joblib
joblib.dump(clf,'clf.m')

['clf.m']